[uwsgi]
module = wsgi:app

master = true
processes = 4
threads = 2
enable-threads = true
single-interpreter = true

socket = /run/zokodaily-api/uwsgi.sock
chmod-socket = 660
vacuum = true

need-app = true
die-on-term = true
lazy-apps = true

harakiri = 60
max-requests = 1000

env = APP_ENV=production
env = FLASK_HOST=127.0.0.1
env = FLASK_PORT=8000

log-date = true
disable-logging = false
